version: '3'
networks:
  bot:
    driver: bridge
services:
  ###############################################
  #### NODEJS APP
  ###############################################
  nodejs-app:
    container_name: bot-nodejs-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "3005:3005"
    env_file:
      - ./.env
    depends_on:
      - mysql
  ###############################################
  #### RESOURCES
  ###############################################
  mysql:
    container_name: bot-mysql
    image: mysql:5.7
    restart: always
    ports:
      - '33065:3306'
    volumes:
      - ./docker/database:/var/lib/mysql
    env_file:
      - ./docker/.env
    networks:
      - bot
  ###############################################
  phpmyadmin:
    container_name: bot-phpmyadmin
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8085:80'
    environment:
      - PMA_VERBOSES=mysql
      - PMA_HOSTS=mysql
    #    env_file:
    #      - ./docker/.env
    networks:
      - bot
  ###############################################
  ngrok:
    container_name: bot-ngrok
    image: wernight/ngrok
    ports:
      - "4040:4040"
    stdin_open: true
    tty: true
    depends_on:
      - nodejs-app
    networks:
      - bot
    environment:
      - NGROK_PORT=host.docker.internal:3005
      - NGROK_REGION=eu
      - NGROK_PROTOCOL=http
      - NGROK_DEBUG=1
  #      - NGROK_AUTH=<>
  #      - NGROK_SUBDOMAIN=<>

